name: Python package build
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Build manylinux Python wheels
      uses: ./.github/actions/build-manylinux
      with:
        python-versions: 'cp37-cp37m'
        build-requirements: ''
        system-packages: 'cmake3 openblas-devel'
        package-path: './python/'
