name: Python package build
on:
  push:
    branches:
      - issue_35

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Build manylinux Python wheels
      uses: ./.github/actions/build-manylinux
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38m'
        build-requirements: ''
        system-packages: 'cmake3 openblas-devel boost-devel devtoolset-9'
        package-path: './python/'
